#!/usr/bin/env node
//
// Generate the mountable plant browser from the database's UI template plus the
// GATED dataset.
//
//   node scripts/build-island.mjs
//
// The database owns the interface; this repo owns what may be said publicly.
// Keeping those separate is the whole point: the template arrives verbatim with a
// /* __PLANTS__ */ placeholder, and the only thing injected is data that has been
// through publish-gate.js. Nothing here decides what is publishable, and nothing
// in the template holds a copy of a species fact.
//
// Output is a build product — gitignored, regenerated before every dev run and
// build, never edited by hand.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ISLAND_OUT, PUBLIC_DATA, SITE_RULES_DATA, SITE_ROOT } from './plant-db-common.mjs';
import { PUBLISHED_IGN_SOURCES, gateAll, withheldCounts } from '../src/lib/publish-gate.js';

const TEMPLATE = join(SITE_ROOT, 'src/components/XericPlantDB.template.jsx');
const PLACEHOLDER = '/* __PLANTS__ */';
const RULES_PLACEHOLDER = '/* __SITERULES__ */';

const template = readFileSync(TEMPLATE, 'utf8');

if (!template.includes(PLACEHOLDER)) {
  console.error(`  template is missing the ${PLACEHOLDER} placeholder.`);
  console.error('  the database changed its template contract — re-check render_jsx.py.');
  process.exit(1);
}

// The site-tuning panel reads SITE_RULES. Leaving this placeholder unfilled
// would ship a component that throws on mount the moment a visitor opens the
// panel — a runtime failure no build step would otherwise catch.
if (!template.includes(RULES_PLACEHOLDER)) {
  console.error(`  template is missing the ${RULES_PLACEHOLDER} placeholder.`);
  console.error('  the database template and this build disagree — re-sync, then');
  console.error('  check render_jsx.py still emits it.');
  process.exit(1);
}

// Gated at sync time. This file is the only species data in the repo.
const gated = JSON.parse(readFileSync(join(SITE_ROOT, PUBLIC_DATA), 'utf8'));

// A withheld rating must arrive as null, not as a number the UI could render.
// hiz() maps null to its "unrated" branch; anything else would state a rating.
const leaked = gated.filter((p) => p.ignWithheld && p.ign !== null);
const srcLeaked = gated.filter((p) => p.ignSrc === 'est');
if (leaked.length || srcLeaked.length) {
  console.error(`  gate failure: ${leaked.length} withheld rating(s) carry a value,`);
  console.error(`                ${srcLeaked.length} record(s) still marked ignSrc "est"`);
  process.exit(1);
}

// The gate must be idempotent: re-applying it to already-gated data has to be a
// no-op. If it is not, the withheld flags are derived from evidence that has already
// been removed, and a second pass silently forgets that anything was withheld.
const before = JSON.stringify(withheldCounts(gated));
const after = JSON.stringify(withheldCounts(gateAll(gated)));
if (before !== after) {
  console.error('  gate is not idempotent — re-gating changed the withheld counts:');
  console.error(`    once: ${before}   twice: ${after}`);
  console.error('  see the IDEMPOTENT note in src/lib/publish-gate.js');
  process.exit(1);
}

// The component ships its own Google Fonts @import for standalone use. On this site
// the host page already serves those families from /fonts, so the import is stripped
// here rather than removed upstream — the database's own standalone view still needs
// it. Without this the page would make a third-party request on every visit,
// disclosing visitor IPs to Google and forcing the CSP to allow an external origin.
const FONT_IMPORT = /^\s*@import url\(['"]https:\/\/fonts\.googleapis\.com[^)]*\);?\s*$/m;

if (!FONT_IMPORT.test(template)) {
  console.error('  expected a Google Fonts @import in the UI template, found none.');
  console.error('  either it moved (adjust the pattern) or it is already gone.');
  console.error('  refusing to build blind — a silent miss would reintroduce a');
  console.error('  third-party request and break the CSP.');
  process.exit(1);
}

const deFonted = template.replace(
  FONT_IMPORT,
  '\n        /* Google Fonts @import removed by build-island.mjs — the host page\n' +
    '           serves these families from /fonts. See src/styles/fonts.css. */\n',
);

const banner = `/* GENERATED by scripts/build-island.mjs — do not edit.
   UI from the plant database's ui/template.jsx; data gated by src/lib/publish-gate.js.
   ${gated.filter((p) => p.ign !== null).length} of ${gated.length} species carry a published fire rating. */`;

const withPlants = deFonted.replace(
  PLACEHOLDER,
  `${banner}\nconst PLANTS = ${JSON.stringify(gated)};`,
);

/* ── Site rules, and the cross-repo gate check ─────────────────────────────
   The database and this repo both hold the rule for which ignitability sources
   count as published — the database in scripts/packs/xeric.py, this repo in
   src/lib/publish-gate.js. Neither can import the other, so the duplication is
   unavoidable; what is avoidable is the two silently drifting apart.

   If the database ever adds a third source, or drops one, the site pages and
   the site-tuning panel beside them would start disagreeing about which plants
   are safe next to a house. That fails the build instead. */
const siteRules = JSON.parse(readFileSync(join(SITE_ROOT, SITE_RULES_DATA), 'utf8'));
const theirs = [...siteRules.publishedIgnSources].sort().join(',');
const ours = [...PUBLISHED_IGN_SOURCES].sort().join(',');
if (theirs !== ours) {
  console.error('  PUBLISH GATE MISMATCH — refusing to build.');
  console.error(`    the database publishes ratings from: ${theirs}`);
  console.error(`    src/lib/publish-gate.js accepts:      ${ours}`);
  console.error('  these decide which plants may sit within 30 ft of a structure.');
  console.error('  reconcile them before building, and re-sync afterwards.');
  process.exit(1);
}

const out = withPlants.replace(
  RULES_PLACEHOLDER,
  `const SITE_RULES = Object.freeze(${JSON.stringify(siteRules)});`,
);

writeFileSync(join(SITE_ROOT, ISLAND_OUT), out);

const counts = withheldCounts(gated);
console.log(
  `  built ${ISLAND_OUT} — ${gated.length} species, ${counts.ign} ratings withheld, ${counts.culture} cultural notes withheld`,
);
