#!/usr/bin/env node
//
// Emit dist/_headers for Cloudflare Pages.
//
//   node scripts/build-headers.mjs        (runs automatically as postbuild)
//
// The Content-Security-Policy's script-src carries a hash for every inline script
// in the build. Those hashes change whenever Astro's island bootstrap changes, so
// they are computed here rather than hardcoded — a stale hardcoded hash would break
// hydration silently, which is worse than having no CSP at all.

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SITE_ROOT } from './plant-db-common.mjs';

const DIST = join(SITE_ROOT, 'dist');

function htmlFiles(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return htmlFiles(full);
    return full.endsWith('.html') ? [full] : [];
  });
}

// Every inline <script> needs a hash. Scripts with a src= are covered by 'self'.
const hashes = new Set();
let external = 0;
for (const file of htmlFiles(DIST)) {
  const html = readFileSync(file, 'utf8');
  for (const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (/\ssrc=/.test(m[1])) {
      external += 1;
      continue;
    }
    if (!m[2].trim()) continue;
    hashes.add(`'sha256-${createHash('sha256').update(m[2]).digest('base64')}'`);
  }
}

const scriptSrc = ["'self'", ...[...hashes].sort()].join(' ');

// style-src needs 'unsafe-inline' and that is NOT removable: the plant browser is a
// React component built entirely from inline style objects (~2,600 style="…"
// attributes), and Astro emits scoped <style> blocks per component. This is a real
// weakening of the policy. It is acceptable here only because the site renders no
// user input anywhere — every value comes from a build-time data file, and the one
// dangerouslySetInnerHTML is a static literal. It should not be read as a general
// statement that inline styles are safe.
const csp = [
  "default-src 'self'",
  `script-src ${scriptSrc}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  // The contact form posts to Formspree. Narrow this if the form is ever removed.
  'form-action https://formspree.io',
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

// NOTE: no Strict-Transport-Security here on purpose. HSTS is a promise that the
// domain will always be reachable over HTTPS, and it is cached by browsers for its
// max-age whether or not that stays true. Add it deliberately once the real domain
// is wired up and confirmed, not before.
const body = `# GENERATED by scripts/build-headers.mjs — do not edit by hand.
# Regenerated on every build; the script-src hashes track the current output.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Cross-Origin-Opener-Policy: same-origin

# Fingerprinted assets are immutable; everything else revalidates.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(join(DIST, '_headers'), body);

console.log(
  `  wrote dist/_headers — ${hashes.size} inline script hash(es), ${external} external script(s)`,
);
